In [1]:
import pandas as pd
d=pd.read_csv('/content/2203A51568.csv')
print(d)

    people  age  height  weight
0     akki   19     140      50
1   chinna   20     150      60
2    vinny   19     145      55
3    nithu   23     160      40
4    sanju   22     145      65
5    bunny   18     165      40
6   manasi   24     140      60
7  archana   23     150      55
8    akhil   19     155      35
9      sai   20     140      40

In [2]:
d=pd.read_excel('/content/2203A51568.xlsx')
print(d)

    people  age  height  weight
0     akki   19     140      50
1   chinna   20     150      60
2    vinny   19     145      55
3    nithu   23     160      40
4    sanju   22     145      65
5    bunny   18     165      40
6   manasi   24     140      60
7  archana   23     150      55
8    akhil   19     155      35
9      sai   20     140      40

In [3]:
d=pd.read_csv('/content/2203A51568.tsv')
print(d)

  people\tage\theight\tweight
0           akki\t19\t140\t50
1         chinna\t20\t150\t60
2          vinny\t19\t145\t55
3          nithu\t23\t160\t40
4          sanju\t22\t145\t65
5          bunny\t18\t165\t40
6         manasi\t24\t140\t60
7        archana\t23\t150\t55
8          akhil\t19\t155\t35
9            sai\t20\t140\t40